# Generated by Django 5.2.13 on 2026-07-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0018_rename_table_mock_table_sender_limit_mock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_sender_limit_mock',
            old_name='ID_SIMULAZIONE',
            new_name='SIMULAZIONE_ID',
        ),
    ]
