# Generated by Django 5.2.13 on 2026-07-09 15:42

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0019_rename_id_simulazione_table_sender_limit_mock_simulazione_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_output_capacity_setting_mock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('PEAK_CAPACITY', models.IntegerField(null=True)),
                ('PRODUCTION_CAPACITY', models.IntegerField(null=True)),
                ('SUM_WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE_MOCK', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('PROVINCIA', models.CharField(max_length=50, null=True)),
                ('COD_SIGLA_PROVINCIA', models.CharField(max_length=5, null=True)),
                ('PRODUCT_890', models.BooleanField(null=True)),
                ('PRODUCT_AR', models.BooleanField(null=True)),
                ('MONTH_DELIVERY', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'output_capacity_setting_mock',
                'managed': False,
            },
        ),
    ]
