# Generated by Django 5.2.13 on 2026-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0020_view_output_capacity_setting_mock'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='table_sender_limit_mock',
            index=models.Index(fields=['SIMULAZIONE_ID'], name='indice_simulazione_id_7'),
        ),
        migrations.AddIndex(
            model_name='table_sender_limit_mock',
            index=models.Index(fields=['DELIVERY_DATE'], name='indice_delivery_date_2'),
        ),
        migrations.AddIndex(
            model_name='table_sender_limit_mock',
            index=models.Index(fields=['SUDDIVISIONE_GEOGRAFICA'], name='indice_suddivisione_geografica'),
        ),
        migrations.AddIndex(
            model_name='table_sender_limit_mock',
            index=models.Index(fields=['LAST_UPDATE_TIMESTAMP'], name='indice_last_update_timestamp_5'),
        ),
    ]
