# Generated by Django 5.2.13 on 2026-07-17 11:12

import Simulatore.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0021_table_sender_limit_mock_indice_simulazione_id_7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_sender_limit_mock',
            name='LAST_UPDATE_TIMESTAMP',
            field=Simulatore.models.NaiveDateTimeField(null=True),
        ),
    ]
