AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  EnvironmentType:
    Type: String
    AllowedValues:
      - dev
      - test
      - uat
      - hotfix
      - prod
    Default: dev

  AlarmSNSTopicArn:
    Type: String
    Description: 'ARN of alarm topic'

  MicroServiceUniqueName:
    Type: String
    Description: 'Unique name for the microservice'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  VPNECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  VPNServicesSubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VPNDefaultSecurityGroupId:
    Type: String
    Description: 'Default security group ID for the VPC'

  VPNVpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'

  VPNVpcCidr:
    Type: String
    Description: 'Source VPC CIDR block for RDS ingress rule'

  VPNApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  VPNWebappSecurityGroupId:
    Type: String
    Description: 'Security group ID for the web application'

  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  RdsSimulatorPort:
    Type: Number
    Description: RDS Cluster Port (from storage stack)

  SimulatorAlbPath:
    Type: String
    Default: /*

  SimulatorHealthCheckPath:
    Type: String
    Default: /status

  # Autoscaling parameters
  AutoscalingCheckPeriod:
    Default: 300
    Type: Number
    Description: 'minimum autoscaling number of tasks'

  AutoscalingDataPointN:
    Default: 1
    Type: Number
    Description: 'activate when N datapoint on M'

  AutoscalingDataPointM:
    Default: 1
    Type: Number
    Description: 'activate when N datapoint on M'

  AutoscalingThreshold:
    Default: 1000
    Type: String
    Description: 'activate when default is reached'

  MinTasksNumber:
    Default: 1
    Type: Number
    Description: 'minimum autoscaling number of tasks'

  MaxTasksNumber:
    Default: 6
    Type: Number
    Description: 'maximum autoscaling number of tasks'

  # OpenApi Bucket params
  MicroserviceBucketName:
    Type: String
    Default: 'default-microservice-bucket'
    Description: 'Name of the bucket where the microservice files are copied during deploy'

  MicroserviceBucketBaseKey:
    Type: String
    Default: ''
    Description: 'Base key of the microservice in the s3 bucket'

  # Log group parameters
  EcsLogGroup:
    Type: String
    Description: 'Ecs log group name'

  LogAlarmStrategy:
    Type: String
    Default: 'FATAL'

  # Heath Check parameters
  HealthCheckInterval:
    Description: 'Seconds between two health check'
    Type: Number
    Default: 60

  HealthCheckTimeout:
    Description: 'health check timeout seconds'
    Type: Number
    Default: 5

  HealthyThresholdCount:
    Description: 'The number of consecutive health checks successes required before considering 
      an unhealthy target healthy.'
    Type: Number
    Default: 5

  UnhealthyThresholdCount:
    Description: 'The number of consecutive health check failures required before considering a target unhealthy.'
    Type: Number
    Default: 2

  # Instance parameters
  # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
  # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
  # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
  # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
  # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments

  SvcSimulatorUsername:
    Description: service user Username
    Type: String

  RdsSimulatorEndpointAddress:
    Description: RDS Cluster Writer Endpoint Address
    Type: String

  RdsSimulatorDbName:
    Description: RDS Database Name
    Type: String

  SvcSimulatorUserSecretArn:
    Description: ARN of the placeholder secret for service user
    Type: String

  AllowedHosts:
    Type: String

  # Glue Parameters
  GlueConnectionName:
    Type: String
    Description: 'Glue connection name for Aurora database'
    Default: 'pn-simulatore-recapiti-glue-network-connection'

  GlueScriptsS3Path:
    Type: String
    Description: 'S3 path where Glue scripts are stored'
    Default: 'scripts/pn-simulatore-recapiti'

  GlueLibsS3Path:
    Type: String
    Description: 'S3 path where Glue libs are stored'
    Default: 'libs/pn-simulatore-recapiti'

  CpuValue:
    Type: Number
    Default: 1024
    Description: 'Fargate virtual CPU quantity 1024 equals one vCPU'

  # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
  # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
  # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
  # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
  # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
  MemoryAmount:
    Type: String
    Default: 2GB
    Description: 'memory amount reserved to the task pod.'
    AllowedValues: [ 2GB, 4GB, 6GB, 8GB ]

Resources:
  SimulatorMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub "${ProjectName}-${MicroServiceUniqueName}"
        CpuValue: !Ref CpuValue
        MemoryAmount: !Ref MemoryAmount
        MappedPaths: !Ref SimulatorAlbPath
        HealthCheckTimeout: !Ref HealthCheckTimeout
        HealthCheckInterval: !Ref HealthCheckInterval
        HealthyThresholdCount: !Ref HealthyThresholdCount
        UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
        HealthCheckPath: !Ref SimulatorHealthCheckPath
        MinTasksNumber: !Ref MinTasksNumber
        MaxTasksNumber: !Ref MaxTasksNumber
        ContainerEnvEntry1: !Sub DB_NAME=${RdsSimulatorDbName}
        ContainerEnvEntry2: !Sub DB_USER=${SvcSimulatorUsername}
        ContainerEnvEntry3: !Sub DB_HOST=${RdsSimulatorEndpointAddress}
        ContainerEnvEntry4: !Sub DB_PORT=${RdsSimulatorPort}
        ContainerEnvEntry5: !Sub ALLOWED_HOSTS=${AllowedHosts}
        ContainerSecret1: !Sub 'DB_PASSWORD=${SvcSimulatorUserSecretArn}:password:AWSCURRENT:'
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Ref ContainerImageUri
        ECSClusterName: !Ref VPNECSClusterName
        Subnets: !Ref VPNServicesSubnetsIds
        VpcId: !Ref VPNVpcId
        AlbSecurityGroup: !Ref VPNWebappSecurityGroupId
        LoadBalancerListenerArn: !Ref VPNApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        EcsLogGroup: !Ref EcsLogGroup
        LogAlarmStrategyV1: !Ref LogAlarmStrategy
        TaskRoleManagedPolicyArn: !Ref SimulatorMicroserviceTaskManagedPolicy
        MicroServiceSecretPrefix: pn-simulatore-recapiti-db-svc-user-credentials

  EcsSimulatorDefaultSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG with specific egress for pn-simulatore-recapiti tasks
      VpcId: !Ref VPNVpcId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: !Ref RdsSimulatorPort
          ToPort: !Ref RdsSimulatorPort
          DestinationSecurityGroupId: !Ref VPNWebappSecurityGroupId
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: pn-simulatore-recapiti-EcsSimulatorDefault-sg
        - Key: Environment
          Value: !Ref EnvironmentType

  SimulatorMicroserviceTaskManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecretManagerAccess
            Effect: Allow
            Action: secretsmanager:GetSecretValue
            Resource: !Ref SvcSimulatorUserSecretArn

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${MicroServiceUniqueName}-lambda-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref SvcSimulatorUserSecretArn
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::${MicroserviceBucketName}/*"
                  - !Sub "arn:aws:s3:::${MicroserviceBucketName}"

  # Glue Service Role
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${MicroServiceUniqueName}-GlueRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueJobPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref SvcSimulatorUserSecretArn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub "arn:aws:s3:::${MicroserviceBucketName}/*"
                  - !Sub "arn:aws:s3:::${MicroserviceBucketName}"
                  - !Sub "arn:aws:s3:::aws-glue-assets-${AWS::AccountId}-${AWS::Region}/*"
                  - !Sub "arn:aws:s3:::aws-glue-assets-${AWS::AccountId}-${AWS::Region}"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws-glue/*"
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeVpcEndpoints
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeVpcs
                Resource: "*"

  # Lambda Functions
  MergeSenderLimitDBFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${MicroServiceUniqueName}-MergeSenderLimitDB"
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref MicroserviceBucketName
        S3Key: !Sub "${MicroserviceBucketBaseKey}lambdas/MergeSenderLimitDB.zip"
      Timeout: 900
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds:
          - !Ref VPNWebappSecurityGroupId
        SubnetIds: !Split [',', !Ref VPNServicesSubnetsIds]
      Environment:
        Variables:
          DB_HOST: !Ref RdsSimulatorEndpointAddress
          DB_PORT: !Ref RdsSimulatorPort
          DB_NAME: !Ref RdsSimulatorDbName
          secretsManager_SecretId: !Ref SvcSimulatorUserSecretArn

  # Glue Jobs
  GenerazioneCsvImportDataJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub "${ProjectName}-${MicroServiceUniqueName}-GenerazioneCsvImportData"
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}/${GlueScriptsS3Path}/GenerazioneCsvImportData.py"
        PythonVersion: "3"
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-disable"
        "--enable-metrics": "true"
        "--enable-spark-ui": "true"
        "--spark-event-logs-path": !Sub "s3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}/sparkHistoryLogs/"
        "--enable-job-insights": "true"
        "--enable-glue-datacatalog": "true"
        "--enable-continuous-cloudwatch-log": "true"
        "--job-language": "python"
        "--TempDir": !Sub "s3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}/temporary/"
        "--extra-py-files": !Sub "s3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}/${GlueLibsS3Path}/"
        "--jdbc_connection": !Sub "jdbc:postgresql://${RdsSimulatorEndpointAddress}:${RdsSimulatorPort}/${RdsSimulatorDbName}"
        "--s3_bucket": !Ref MicroserviceBucketName
        "--secretsManager_SecretId": !Ref SvcSimulatorUserSecretArn
      MaxRetries: 0
      Timeout: 480
      GlueVersion: "5.0"
      WorkerType: G.1X
      NumberOfWorkers: 2
      ExecutionClass: STANDARD
      Connections:
        Connections:
          - !Ref GlueConnectionName
      ExecutionProperty:
        MaxConcurrentRuns: 1