# Generated by Django 5.2.6 on 2025-10-09 09:39

import Simulatore.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_simulazione',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('NOME', models.CharField(max_length=50, null=True)),
                ('DESCRIZIONE', models.TextField(null=True)),
                ('STATO', models.CharField(max_length=20, null=True)),
                ('TIMESTAMP_ESECUZIONE', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'SIMULAZIONE',
            },
        ),
        migrations.CreateModel(
            name='table_capacita_modificate',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('MESE_SIMULAZIONE', models.CharField(max_length=20, null=True)),
                ('TIPO_CAPACITA', models.CharField(max_length=25, null=True)),
                ('RECAPITISTA', models.CharField(max_length=50, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('PROVINCIA', models.CharField(max_length=50, null=True)),
                ('POSTALIZZAZIONI', models.IntegerField(null=True)),
                ('CAPACITA', models.IntegerField(null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('SIMULAZIONE_ID', models.ForeignKey(db_column='SIMULAZIONE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Simulatore.table_simulazione')),
            ],
            options={
                'db_table': 'CAPACITA_MODIFICATE',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='table_simulazione',
            name='UTENTE_ID',
            field=models.ForeignKey(db_column='UTENTE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='table_simulazione',
            index=models.Index(fields=['STATO'], name='INDICE_STATO'),
        ),
    ]
