# Generated by Django 5.2.6 on 2025-10-06 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_simulazione',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('NOME', models.CharField(max_length=50)),
                ('DESCRIZIONE', models.TextField()),
                ('UTENTE', models.CharField(max_length=50)),
                ('STATO', models.CharField(choices=[('Lavorata', 'Lavorata'), ('In lavorazione', 'In lavorazione'), ('Schedulata', 'Schedulata'), ('Non completata', 'Non completata'), ('Bozza', 'Bozza')], db_index=True, max_length=20)),
                ('TIMESTAMP_ESECUZIONE', models.DateTimeField()),
            ],
            options={
                'db_table': 'SIMULAZIONE',
            },
        ),
        migrations.CreateModel(
            name='table_capacita_modificate',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('MESE_SIMULAZIONE', models.CharField(max_length=20)),
                ('TIPO_CAPACITA', models.CharField(max_length=20)),
                ('RECAPITISTA', models.CharField(max_length=20)),
                ('GEOKEY', models.CharField(max_length=20)),
                ('CAPACITA', models.CharField(max_length=20)),
                ('ACTIVATION_DATE_FROM', models.DateField()),
                ('ACTIVATION_DATE_TO', models.DateField()),
                ('SIMULAZIONE_ID', models.ForeignKey(db_column='SIMULAZIONE_ID', on_delete=django.db.models.deletion.CASCADE, to='Simulatore.table_simulazione')),
            ],
            options={
                'db_table': 'CAPACITA_MODIFICATE',
            },
        ),
    ]
