# Generated by Django 5.2.6 on 2025-11-03 10:14

import Simulatore.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='view_output_capacity_setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('PEAK_CAPACITY', models.IntegerField(null=True)),
                ('SUM_WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('COD_SIGLA_PROVINCIA', models.CharField(max_length=5, null=True)),
                ('PROVINCIA', models.CharField(max_length=50, null=True)),
                ('PRODUCT_890', models.BooleanField(max_length=5, null=True)),
                ('PRODUCT_AR', models.BooleanField(max_length=5, null=True)),
                ('MONTH_DELIVERY', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'output_capacity_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_output_grafico_ente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('SENDER_PA_ID', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('COUNT_REQUEST', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'output_grafico_ente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_output_grafico_mappa_picchi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('FLAG_PICCO', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'output_grafico_mappa_picchi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_output_grafico_reg_recap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('COUNT_REQUEST', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'output_grafico_reg_recap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_output_modified_capacity_setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ORIGINAL_CAPACITY', models.IntegerField(null=True)),
                ('MODIFIED_CAPACITY', models.IntegerField(null=True)),
                ('SUM_WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('COD_SIGLA_PROVINCIA', models.CharField(max_length=5, null=True)),
                ('PROVINCIA', models.CharField(max_length=50, null=True)),
                ('PRODUCT_890', models.BooleanField(max_length=5, null=True)),
                ('PRODUCT_AR', models.BooleanField(max_length=5, null=True)),
                ('MONTH_DELIVERY', models.SmallIntegerField(null=True)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'output_modified_capacity_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='table_cap_prov_reg',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('CAP', models.CharField(max_length=5, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('PROVINCIA', models.CharField(max_length=50, null=True)),
                ('COD_SIGLA_PROVINCIA', models.CharField(max_length=5, null=True)),
                ('POP_CAP', models.IntegerField(null=True)),
                ('PERCENTUALE_POP_CAP', models.DecimalField(decimal_places=9, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'CAP_PROV_REG',
            },
        ),
        migrations.CreateModel(
            name='table_declared_capacity',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('GEOKEY', models.CharField(max_length=5, null=True)),
                ('TENDER_ID_GEOKEY', models.CharField(max_length=11, null=True)),
                ('PRODUCT_890', models.BooleanField(null=True)),
                ('PRODUCT_AR', models.BooleanField(null=True)),
                ('PRODUCT_RS', models.BooleanField(null=True)),
                ('TENDER_ID', models.CharField(max_length=8, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('CREATED_AT', Simulatore.models.NaiveDateTimeField(null=True)),
                ('PEAK_CAPACITY', models.IntegerField(null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('PK', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'DECLARED_CAPACITY',
            },
        ),
        migrations.CreateModel(
            name='table_results',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PK', models.CharField(max_length=80, null=True)),
                ('SK', models.CharField(max_length=80, null=True)),
                ('ATTEMPT', models.IntegerField(null=True)),
                ('CAP', models.CharField(max_length=5, null=True)),
                ('CREATED_AT', Simulatore.models.NaiveDateTimeField(null=True)),
                ('IUN', models.CharField(max_length=80, null=True)),
                ('NOTIFICATION_SENT_AT', Simulatore.models.NaiveDateTimeField(null=True)),
                ('PREPARE_REQUEST_DATE', Simulatore.models.NaiveDateTimeField(null=True)),
                ('PRIORITY', models.IntegerField(null=True)),
                ('PRODUCT_TYPE', models.CharField(max_length=3, null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('REQUEST_ID', models.CharField(max_length=200, null=True)),
                ('SENDER_PA_ID', models.CharField(max_length=80, null=True)),
                ('TENDER_ID', models.CharField(max_length=8, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'RESULTS',
            },
        ),
        migrations.CreateModel(
            name='table_sender_limit',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PK', models.CharField(max_length=80, null=True)),
                ('DELIVERY_DATE', models.DateField(null=True)),
                ('WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('ORIGINAL_ESTIMATE', models.IntegerField(null=True)),
                ('PA_ID', models.CharField(max_length=80, null=True)),
                ('PRODUCT_TYPE', models.CharField(max_length=3, null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
            ],
            options={
                'db_table': 'SENDER_LIMIT',
            },
        ),
        migrations.CreateModel(
            name='table_simulazione',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('NOME', models.CharField(max_length=50, null=True)),
                ('DESCRIZIONE', models.TextField(null=True)),
                ('STATO', models.CharField(max_length=20, null=True)),
                ('TRIGGER', models.CharField(max_length=10, null=True)),
                ('TIMESTAMP_ESECUZIONE', Simulatore.models.NaiveDateTimeField(null=True)),
                ('MESE_SIMULAZIONE', models.CharField(max_length=20, null=True)),
                ('TIPO_CAPACITA', models.CharField(max_length=25, null=True)),
                ('TIPO_SIMULAZIONE', models.CharField(max_length=25, null=True)),
            ],
            options={
                'db_table': 'SIMULAZIONE',
                'indexes': [models.Index(fields=['STATO'], name='INDICE_STATO')],
            },
        ),
        migrations.CreateModel(
            name='table_capacita_simulate',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('SUM_WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('COD_SIGLA_PROVINCIA', models.CharField(max_length=5, null=True)),
                ('PRODUCT_890', models.BooleanField(max_length=5, null=True)),
                ('PRODUCT_AR', models.BooleanField(max_length=5, null=True)),
                ('SIMULAZIONE_ID', models.ForeignKey(db_column='SIMULAZIONE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Simulatore.table_simulazione')),
            ],
            options={
                'db_table': 'CAPACITA_SIMULATE',
            },
        ),
    ]
