# Generated by Django 5.2.6 on 2025-11-07 01:00

import Simulatore.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_output_grafico_ente',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('SENDER_PA_ID', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('COUNT_REQUEST', models.IntegerField(null=True)),
                ('SIMULAZIONE_ID', models.ForeignKey(db_column='SIMULAZIONE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Simulatore.table_simulazione')),
            ],
            options={
                'db_table': 'OUTPUT_GRAFICO_ENTE',
            },
        ),
        migrations.CreateModel(
            name='table_output_grafico_reg_recap',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('PROVINCIA_RECAPITISTA', models.CharField(max_length=100, null=True)),
                ('COUNT_REQUEST', models.IntegerField(null=True)),
                ('SIMULAZIONE_ID', models.ForeignKey(db_column='SIMULAZIONE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Simulatore.table_simulazione')),
            ],
            options={
                'db_table': 'OUTPUT_GRAFICO_REG_RECAP',
            },
        ),
    ]
