# Generated by Django 5.2.6 on 2025-11-07 00:16

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_output_capacity_setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('PEAK_CAPACITY', models.IntegerField(null=True)),
                ('PRODUCTION_CAPACITY', models.IntegerField(null=True)),
                ('SUM_WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('COD_SIGLA_PROVINCIA', models.CharField(max_length=5, null=True)),
                ('PROVINCIA', models.CharField(max_length=50, null=True)),
                ('PRODUCT_890', models.BooleanField(max_length=5, null=True)),
                ('PRODUCT_AR', models.BooleanField(max_length=5, null=True)),
                ('MONTH_DELIVERY', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'output_capacity_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_output_modified_capacity_setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ORIGINAL_CAPACITY', models.IntegerField(null=True)),
                ('MODIFIED_CAPACITY', models.IntegerField(null=True)),
                ('SUM_WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('COD_SIGLA_PROVINCIA', models.CharField(max_length=5, null=True)),
                ('PROVINCIA', models.CharField(max_length=50, null=True)),
                ('PRODUCT_890', models.BooleanField(max_length=5, null=True)),
                ('PRODUCT_AR', models.BooleanField(max_length=5, null=True)),
                ('MONTH_DELIVERY', models.SmallIntegerField(null=True)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'output_modified_capacity_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_output_tabella_picchi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('TOT_PICCO', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'output_tabella_picchi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_output_grafico_mappa_picchi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('PROP_PICCO', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('FASCIA_PICCO', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'output_grafico_mappa_picchi',
                'managed': False,
            },
        ),
    ]
