# Generated by Django 5.2.6 on 2025-10-17 17:13

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_output_capacity_setting',
        ),
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='ACTIVATION_DATE_FROM',
            new_name='ACTIVATIONDATEFROM',
        ),
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='ACTIVATION_DATE_TO',
            new_name='ACTIVATIONDATETO',
        ),
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='CAPACITA',
            new_name='CAPACITY',
        ),
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='POSTALIZZAZIONI',
            new_name='PEAKCAPACITY',
        ),
        migrations.RenameField(
            model_name='table_declared_capacity',
            old_name='USEDCAPACITY',
            new_name='PEAKCAPACITY',
        ),
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='MESE_SIMULAZIONE',
        ),
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='PROVINCIA',
        ),
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='RECAPITISTA',
        ),
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='REGIONE',
        ),
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='TIPO_CAPACITA',
        ),
        migrations.RemoveField(
            model_name='table_declared_capacity',
            name='DELIVERYDATE',
        ),
        migrations.RemoveField(
            model_name='table_declared_capacity',
            name='UNIFIEDDELIVERYDRIVERGEOKEY',
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='CREATEDAT',
            field=Simulatore.models.NaiveDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='GEOKEY',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='PK',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='PRODUCT_890',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='PRODUCT_AR',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='PRODUCT_RS',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='TENDERID',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='TENDERIDGEOKEY',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='UNIFIEDDELIVERYDRIVER',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='table_declared_capacity',
            name='ACTIVATIONDATEFROM',
            field=Simulatore.models.NaiveDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='table_declared_capacity',
            name='ACTIVATIONDATETO',
            field=Simulatore.models.NaiveDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='table_declared_capacity',
            name='CREATEDAT',
            field=Simulatore.models.NaiveDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='table_declared_capacity',
            name='PK',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table_declared_capacity',
            name='PRODUCT_890',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='table_declared_capacity',
            name='PRODUCT_AR',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='table_declared_capacity',
            name='PRODUCT_RS',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='table_declared_capacity',
            name='TENDERID',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='table_declared_capacity',
            name='TENDERIDGEOKEY',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='table_simulazione',
            name='MESE_SIMULAZIONE',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='table_simulazione',
            name='TIPO_CAPACITA',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
