# Generated by Django 5.2.6 on 2025-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_simulazione',
            name='STATO',
            field=models.CharField(choices=[('Lavorata', 'Lavorata'), ('In lavorazione', 'In lavorazione'), ('Schedulata', 'Schedulata'), ('Non completata', 'Non completata'), ('Bozza', 'Bozza')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='table_simulazione',
            index=models.Index(fields=['STATO'], name='INDICE_STATO'),
        ),
    ]
