# Generated by Django 5.2.6 on 2025-11-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table_output_grafico_ente',
            table='OUTPUT_GRAFICO_ENTI',
        ),
        migrations.AlterModelTable(
            name='table_output_grafico_reg_recap',
            table='OUTPUT_GRAFICO_REGIONI_RECAPITISTA',
        ),
    ]
