# Generated by Django 5.2.6 on 2025-10-09 09:40

import Simulatore.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_simulazione',
            name='TIMESTAMP_ESECUZIONE',
            field=Simulatore.models.NaiveDateTimeField(null=True),
        ),
    ]
