# Generated by Django 5.2.6 on 2025-11-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0002_view_output_tabella_picchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_capacita_simulate',
            name='SUM_MONTHLY_ESTIMATE',
            field=models.IntegerField(null=True),
        ),
    ]
