# Generated by Django 5.2.6 on 2025-10-09 16:37

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0002_alter_table_simulazione_timestamp_esecuzione'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_declared_capacity',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('UNIFIEDDELIVERYDRIVERGEOKEY', models.CharField(max_length=80, null=True)),
                ('DELIVERYDATE', Simulatore.models.NaiveDateTimeField(null=True)),
                ('GEOKEY', models.CharField(max_length=5, null=True)),
                ('UNIFIEDDELIVERYDRIVER', models.CharField(max_length=80, null=True)),
                ('USEDCAPACITY', models.IntegerField(null=True)),
                ('CAPACITY', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'DECLARED_CAPACITY',
            },
        ),
        migrations.CreateModel(
            name='table_sender_limit',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PK', models.CharField(max_length=80, null=True)),
                ('DELIVERYDATE', models.DateField(null=True)),
                ('WEEKLYESTIMATE', models.IntegerField(null=True)),
                ('MONTHLYESTIMATE', models.IntegerField(null=True)),
                ('ORIGINALESTIMATE', models.IntegerField(null=True)),
                ('PAID', models.CharField(max_length=80, null=True)),
                ('PRODUCTTYPE', models.CharField(max_length=3, null=True)),
                ('PROVINCE', models.CharField(max_length=2, null=True)),
            ],
            options={
                'db_table': 'SENDER_LIMIT',
            },
        ),
    ]
