# Generated by Django 5.2.6 on 2025-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0002_delete_table_output_capacity_setting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_cap_prov_reg',
            name='CODSIGLAPROVINCIA',
        ),
        migrations.RemoveField(
            model_name='table_cap_prov_reg',
            name='DESCRMACROREGIONE',
        ),
        migrations.AddField(
            model_name='table_cap_prov_reg',
            name='COD_SIGLA_PROVINCIA',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='table_cap_prov_reg',
            name='PERCENTUALE_POP_CAP',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='table_cap_prov_reg',
            name='POP_CAP',
            field=models.IntegerField(null=True),
        ),
    ]
