# Generated by Django 5.2.6 on 2025-11-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0002_alter_table_output_grafico_ente_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='view_output_grafico_mappa_picchi',
        ),
        migrations.DeleteModel(
            name='view_output_tabella_picchi',
        ),
        migrations.AlterModelTable(
            name='table_output_grafico_ente',
            table='OUTPUT_GRAFICO_ENTE',
        ),
        migrations.AlterModelTable(
            name='table_output_grafico_reg_recap',
            table='OUTPUT_GRAFICO_REG_RECAP',
        ),
    ]
