# Generated by Django 5.2.6 on 2025-11-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0003_tabelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_output_grafico_mappa_picchi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('PROP_PICCO', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('FASCIA_PICCO', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'output_grafico_mappa_picchi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_output_tabella_picchi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('TOT_PICCO', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'output_tabella_picchi',
                'managed': False,
            },
        ),
    ]
