# Generated by Django 5.2.6 on 2025-11-04 17:27

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0003_table_capacita_simulate_sum_monthly_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_declared_capacity',
            name='LAST_UPDATE_TIMESTAMP',
            field=Simulatore.models.NaiveDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='table_declared_capacity',
            name='PRODUCTION_CAPACITY',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table_sender_limit',
            name='LAST_UPDATE_TIMESTAMP',
            field=Simulatore.models.NaiveDateTimeField(null=True),
        ),
    ]
