# Generated by Django 5.2.6 on 2025-11-20 00:18

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0003_view_output_capacity_setting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_capacita_simulate_delta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('SUM_WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('COD_SIGLA_PROVINCIA', models.CharField(max_length=5, null=True)),
                ('PRODUCT_890', models.BooleanField(max_length=5, null=True)),
                ('PRODUCT_AR', models.BooleanField(max_length=5, null=True)),
                ('LAST_UPDATE_TIMESTAMP', Simulatore.models.NaiveDateTimeField(null=True)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'CAPACITA_SIMULATE_DELTA',
            },
        ),
        migrations.RemoveIndex(
            model_name='table_simulazione',
            name='INDICE_STATO',
        ),
        migrations.AddField(
            model_name='table_capacita_simulate',
            name='LAST_UPDATE_TIMESTAMP',
            field=Simulatore.models.NaiveDateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='table_cap_prov_reg',
            index=models.Index(fields=['REGIONE'], name='indice_regione_2'),
        ),
        migrations.AddIndex(
            model_name='table_cap_prov_reg',
            index=models.Index(fields=['PROVINCIA'], name='indice_provincia'),
        ),
        migrations.AddIndex(
            model_name='table_cap_prov_reg',
            index=models.Index(fields=['COD_SIGLA_PROVINCIA'], name='indice_cod_sigla_provincia_2'),
        ),
        migrations.AddIndex(
            model_name='table_capacita_simulate',
            index=models.Index(fields=['SIMULAZIONE_ID'], name='indice_simulazione_id'),
        ),
        migrations.AddIndex(
            model_name='table_capacita_simulate',
            index=models.Index(fields=['ACTIVATION_DATE_FROM'], name='indice_activation_date_from'),
        ),
        migrations.AddIndex(
            model_name='table_capacita_simulate',
            index=models.Index(fields=['ACTIVATION_DATE_TO'], name='indice_activation_date_to'),
        ),
        migrations.AddIndex(
            model_name='table_capacita_simulate',
            index=models.Index(fields=['UNIFIED_DELIVERY_DRIVER'], name='indice_unified_delivery_driver'),
        ),
        migrations.AddIndex(
            model_name='table_capacita_simulate',
            index=models.Index(fields=['COD_SIGLA_PROVINCIA'], name='indice_cod_sigla_provincia'),
        ),
        migrations.AddIndex(
            model_name='table_capacita_simulate',
            index=models.Index(fields=['CAPACITY'], name='indice_capacity'),
        ),
        migrations.AddIndex(
            model_name='table_capacita_simulate',
            index=models.Index(fields=['REGIONE'], name='indice_regione'),
        ),
        migrations.AddIndex(
            model_name='table_declared_capacity',
            index=models.Index(fields=['GEOKEY'], name='indice_geokey'),
        ),
        migrations.AddIndex(
            model_name='table_declared_capacity',
            index=models.Index(fields=['ACTIVATION_DATE_FROM'], name='indice_activation_date_from_2'),
        ),
        migrations.AddIndex(
            model_name='table_declared_capacity',
            index=models.Index(fields=['ACTIVATION_DATE_TO'], name='indice_activation_date_to_2'),
        ),
        migrations.AddIndex(
            model_name='table_declared_capacity',
            index=models.Index(fields=['UNIFIED_DELIVERY_DRIVER'], name='indice_unified_delivery_driv_2'),
        ),
        migrations.AddIndex(
            model_name='table_declared_capacity',
            index=models.Index(fields=['PK'], name='indice_pk'),
        ),
        migrations.AddIndex(
            model_name='table_declared_capacity',
            index=models.Index(fields=['LAST_UPDATE_TIMESTAMP'], name='indice_last_update_timestamp'),
        ),
        migrations.AddIndex(
            model_name='table_output_grafico_ente',
            index=models.Index(fields=['SIMULAZIONE_ID'], name='indice_simulazione_id_2'),
        ),
        migrations.AddIndex(
            model_name='table_output_grafico_ente',
            index=models.Index(fields=['SENDER_PA_ID'], name='indice_sender_pa_id'),
        ),
        migrations.AddIndex(
            model_name='table_output_grafico_reg_recap',
            index=models.Index(fields=['SIMULAZIONE_ID'], name='indice_simulazione_id_3'),
        ),
        migrations.AddIndex(
            model_name='table_output_grafico_reg_recap',
            index=models.Index(fields=['REGIONE'], name='indice_regione_3'),
        ),
        migrations.AddIndex(
            model_name='table_output_grafico_reg_recap',
            index=models.Index(fields=['UNIFIED_DELIVERY_DRIVER'], name='indice_unified_delivery_driv_3'),
        ),
        migrations.AddIndex(
            model_name='table_output_grafico_reg_recap',
            index=models.Index(fields=['PROVINCE'], name='indice_province_2'),
        ),
        migrations.AddIndex(
            model_name='table_output_grafico_reg_recap',
            index=models.Index(fields=['SETTIMANA_DELIVERY'], name='indice_settimana_delivery'),
        ),
        migrations.AddIndex(
            model_name='table_output_grafico_reg_recap',
            index=models.Index(fields=['COUNT_REQUEST'], name='indice_count_request'),
        ),
        migrations.AddIndex(
            model_name='table_sender_limit',
            index=models.Index(fields=['DELIVERY_DATE'], name='indice_delivery_date'),
        ),
        migrations.AddIndex(
            model_name='table_sender_limit',
            index=models.Index(fields=['PROVINCE'], name='indice_province'),
        ),
        migrations.AddIndex(
            model_name='table_sender_limit',
            index=models.Index(fields=['PK'], name='indice_pk_2'),
        ),
        migrations.AddIndex(
            model_name='table_sender_limit',
            index=models.Index(fields=['LAST_UPDATE_TIMESTAMP'], name='indice_last_update_timestamp_2'),
        ),
        migrations.AddIndex(
            model_name='table_simulazione',
            index=models.Index(fields=['MESE_SIMULAZIONE'], name='indice_mese_simulazione'),
        ),
        migrations.AddIndex(
            model_name='table_simulazione',
            index=models.Index(fields=['TIMESTAMP_ESECUZIONE'], name='indice_timestamp_esecuzione'),
        ),
    ]
