# Generated by Django 5.2.6 on 2025-10-20 11:18

import Simulatore.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0003_remove_table_cap_prov_reg_codsiglaprovincia_and_more'),
    ]

    operations = [
    ]
