# Generated by Django 5.2.6 on 2025-10-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
