# Generated by Django 5.2.6 on 2025-10-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0003_table_declared_capacity_table_sender_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_sender_limit',
            name='PROVINCE',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
