# Generated by Django 5.2.6 on 2025-10-20 14:53

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0004_alter_table_cap_prov_reg_percentuale_pop_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_output_capacity_setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UNIFIEDDELIVERYDRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATIONDATEFROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATIONDATETO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('SUM_WEEKLYESTIMATE', models.IntegerField(null=True)),
                ('SUM_MONTHLYESTIMATE', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('PRODUCT_890', models.BooleanField(max_length=5, null=True)),
                ('PRODUCT_AR', models.BooleanField(max_length=5, null=True)),
                ('MONTH_DELIVERY', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'output_capacity_setting',
                'managed': False,
            },
        ),
    ]
