# Generated by Django 5.2.6 on 2025-10-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0004_alter_table_sender_limit_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_cap_prov_reg',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('CAP', models.CharField(max_length=5, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('PROVINCIA', models.CharField(max_length=50, null=True)),
                ('CODSIGLAPROVINCIA', models.CharField(max_length=2, null=True)),
                ('DESCRMACROREGIONE', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'CAP_PROV_REG',
            },
        ),
    ]
