# Generated by Django 5.2.6 on 2025-11-06 16:13

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0004_table_declared_capacity_last_update_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_output_grafico_ente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('SENDER_PA_ID', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('COUNT_REQUEST', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'OUTPUT_GRAFICO_ENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='table_output_grafico_reg_recap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('PROVINCIA_RECAPITISTA', models.CharField(max_length=100, null=True)),
                ('COUNT_REQUEST', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'OUTPUT_GRAFICO_REG_RECAP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='table_declared_capacity_delta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('GEOKEY', models.CharField(max_length=5, null=True)),
                ('TENDER_ID_GEOKEY', models.CharField(max_length=11, null=True)),
                ('PRODUCT_890', models.BooleanField(null=True)),
                ('PRODUCT_AR', models.BooleanField(null=True)),
                ('PRODUCT_RS', models.BooleanField(null=True)),
                ('TENDER_ID', models.CharField(max_length=8, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('CREATED_AT', Simulatore.models.NaiveDateTimeField(null=True)),
                ('PEAK_CAPACITY', models.IntegerField(null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('PK', models.CharField(max_length=100, null=True)),
                ('PRODUCTION_CAPACITY', models.IntegerField(null=True)),
                ('LAST_UPDATE_TIMESTAMP', Simulatore.models.NaiveDateTimeField(null=True)),
            ],
            options={
                'db_table': 'DECLARED_CAPACITY_DELTA',
            },
        ),
        migrations.CreateModel(
            name='table_sender_limit_delta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PK', models.CharField(max_length=80, null=True)),
                ('DELIVERY_DATE', models.DateField(null=True)),
                ('WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('ORIGINAL_ESTIMATE', models.IntegerField(null=True)),
                ('PA_ID', models.CharField(max_length=80, null=True)),
                ('PRODUCT_TYPE', models.CharField(max_length=3, null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('LAST_UPDATE_TIMESTAMP', Simulatore.models.NaiveDateTimeField(null=True)),
            ],
            options={
                'db_table': 'SENDER_LIMIT_DELTA',
            },
        ),
        migrations.DeleteModel(
            name='table_results',
        ),
        migrations.DeleteModel(
            name='view_output_grafico_ente',
        ),
        migrations.DeleteModel(
            name='view_output_grafico_reg_recap',
        ),
    ]
