# Generated by Django 5.2.6 on 2025-12-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0004_table_capacita_simulate_delta_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='table_cap_prov_reg',
            name='indice_regione_2',
        ),
        migrations.RemoveIndex(
            model_name='table_capacita_simulate',
            name='indice_unified_delivery_driver',
        ),
        migrations.RemoveIndex(
            model_name='table_capacita_simulate',
            name='indice_regione',
        ),
        migrations.RemoveIndex(
            model_name='table_declared_capacity',
            name='indice_unified_delivery_driv_2',
        ),
        migrations.RemoveIndex(
            model_name='table_output_grafico_reg_recap',
            name='indice_regione_3',
        ),
        migrations.RemoveIndex(
            model_name='table_output_grafico_reg_recap',
            name='indice_unified_delivery_driv_3',
        ),
        migrations.AlterField(
            model_name='table_capacita_simulate',
            name='PRODUCT_890',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='table_capacita_simulate',
            name='PRODUCT_AR',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='table_capacita_simulate_delta',
            name='PRODUCT_890',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='table_capacita_simulate_delta',
            name='PRODUCT_AR',
            field=models.BooleanField(null=True),
        ),
        migrations.AddIndex(
            model_name='table_capacita_simulate',
            index=models.Index(fields=['LAST_UPDATE_TIMESTAMP'], name='indice_last_update_timestamp_3'),
        ),
        migrations.AddIndex(
            model_name='table_output_grafico_ente',
            index=models.Index(fields=['SETTIMANA_DELIVERY'], name='indice_settimana_delivery_2'),
        ),
    ]
