# Generated by Django 5.2.6 on 2025-11-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0005_table_output_grafico_ente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table_output_grafico_ente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='table_output_grafico_reg_recap',
            options={},
        ),
    ]
