# Generated by Django 5.2.6 on 2025-10-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0005_table_auth_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table_auth_user',
        ),
    ]
