# Generated by Django 5.2.6 on 2025-10-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0005_table_cap_prov_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_cap_prov_reg',
            name='CODSIGLAPROVINCIA',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
