# Generated by Django 5.2.6 on 2025-10-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0005_table_output_capacity_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_cap_prov_reg',
            name='PERCENTUALE_POP_CAP',
            field=models.DecimalField(decimal_places=9, max_digits=11, null=True),
        ),
    ]
