# Generated by Django 5.2.6 on 2026-03-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0005_remove_table_cap_prov_reg_indice_regione_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_capacita_simulate',
            name='FLAG_DEFAULT',
            field=models.BooleanField(null=True),
        ),
    ]
