# Generated by Django 5.2.6 on 2026-03-10 11:19

import Simulatore.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0006_table_capacita_simulate_flag_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_capacita_simulate_cap',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('SUM_WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('COD_SIGLA_PROVINCIA', models.CharField(max_length=5, null=True)),
                ('GEOKEY', models.CharField(max_length=5, null=True)),
                ('PRODUCT_890', models.BooleanField(null=True)),
                ('PRODUCT_AR', models.BooleanField(null=True)),
                ('LAST_UPDATE_TIMESTAMP', Simulatore.models.NaiveDateTimeField(null=True)),
                ('SIMULAZIONE_ID', models.ForeignKey(db_column='SIMULAZIONE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Simulatore.table_simulazione')),
            ],
            options={
                'db_table': 'CAPACITA_SIMULATE_CAP',
            },
        ),
    ]
