# Generated by Django 5.2.6 on 2025-10-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0006_alter_table_cap_prov_reg_percentuale_pop_cap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='ACTIVATIONDATEFROM',
            new_name='ACTIVATION_DATE_FROM',
        ),
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='ACTIVATIONDATETO',
            new_name='ACTIVATION_DATE_TO',
        ),
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='CREATEDAT',
            new_name='CREATED_AT',
        ),
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='PEAKCAPACITY',
            new_name='PEAK_CAPACITY',
        ),
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='TENDERID',
            new_name='TENDER_ID',
        ),
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='TENDERIDGEOKEY',
            new_name='TENDER_ID_GEOKEY',
        ),
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='UNIFIEDDELIVERYDRIVER',
            new_name='UNIFIED_DELIVERY_DRIVER',
        ),
        migrations.RenameField(
            model_name='table_declared_capacity',
            old_name='ACTIVATIONDATEFROM',
            new_name='ACTIVATION_DATE_FROM',
        ),
        migrations.RenameField(
            model_name='table_declared_capacity',
            old_name='ACTIVATIONDATETO',
            new_name='ACTIVATION_DATE_TO',
        ),
        migrations.RenameField(
            model_name='table_declared_capacity',
            old_name='CREATEDAT',
            new_name='CREATED_AT',
        ),
        migrations.RenameField(
            model_name='table_declared_capacity',
            old_name='PEAKCAPACITY',
            new_name='PEAK_CAPACITY',
        ),
        migrations.RenameField(
            model_name='table_declared_capacity',
            old_name='TENDERIDGEOKEY',
            new_name='TENDER_ID_GEOKEY',
        ),
        migrations.RenameField(
            model_name='table_declared_capacity',
            old_name='UNIFIEDDELIVERYDRIVER',
            new_name='UNIFIED_DELIVERY_DRIVER',
        ),
        migrations.RenameField(
            model_name='table_sender_limit',
            old_name='DELIVERYDATE',
            new_name='DELIVERY_DATE',
        ),
        migrations.RenameField(
            model_name='table_sender_limit',
            old_name='MONTHLYESTIMATE',
            new_name='MONTHLY_ESTIMATE',
        ),
        migrations.RenameField(
            model_name='table_sender_limit',
            old_name='ORIGINALESTIMATE',
            new_name='ORIGINAL_ESTIMATE',
        ),
        migrations.RenameField(
            model_name='table_sender_limit',
            old_name='PAID',
            new_name='PA_ID',
        ),
        migrations.RenameField(
            model_name='table_sender_limit',
            old_name='PRODUCTTYPE',
            new_name='PRODUCT_TYPE',
        ),
        migrations.RenameField(
            model_name='table_sender_limit',
            old_name='WEEKLYESTIMATE',
            new_name='WEEKLY_ESTIMATE',
        ),
    ]
