# Generated by Django 5.2.6 on 2025-10-07 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0006_delete_table_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_simulazione',
            name='UTENTE',
        ),
        migrations.AddField(
            model_name='table_simulazione',
            name='UTENTE_ID',
            field=models.ForeignKey(db_column='UTENTE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
