# Generated by Django 5.2.6 on 2025-10-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0006_alter_table_cap_prov_reg_codsiglaprovincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_output_capacity_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNIFIEDDELIVERYDRIVER', models.CharField(max_length=80, null=True)),
                ('DELIVERYDATE', models.DateTimeField(null=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('SUM_WEEKLYESTIMATE', models.IntegerField(null=True)),
                ('SUM_MONTHLYESTIMATE', models.IntegerField(null=True)),
                ('SUM_ORIGINALESTIMATE', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
            ],
            options={
                'db_table': 'OUTPUT_CAPACITY_SETTING',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='table_declared_capacity',
            name='DELIVERYDATE',
            field=models.DateField(null=True),
        ),
    ]
