# Generated by Django 5.2.6 on 2026-03-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0007_table_capacita_simulate_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_capacita_simulate_cap',
            name='COD_SIGLA_PROVINCIA',
        ),
        migrations.RemoveField(
            model_name='table_capacita_simulate_cap',
            name='PRODUCT_890',
        ),
        migrations.RemoveField(
            model_name='table_capacita_simulate_cap',
            name='PRODUCT_AR',
        ),
        migrations.RemoveField(
            model_name='table_capacita_simulate_cap',
            name='REGIONE',
        ),
        migrations.RemoveField(
            model_name='table_capacita_simulate_cap',
            name='SUM_MONTHLY_ESTIMATE',
        ),
        migrations.RemoveField(
            model_name='table_capacita_simulate_cap',
            name='SUM_WEEKLY_ESTIMATE',
        ),
        migrations.AddField(
            model_name='table_capacita_simulate_cap',
            name='PEAK_CAPACITY',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_simulate_delta',
            name='FLAG_DEFAULT',
            field=models.BooleanField(null=True),
        ),
    ]
