# Generated by Django 5.2.6 on 2025-10-21 14:49

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0007_rename_activationdatefrom_table_capacita_modificate_activation_date_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_output_capacity_setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('PEAK_CAPACITY', models.IntegerField(null=True)),
                ('SUM_WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('PRODUCT_890', models.BooleanField(max_length=5, null=True)),
                ('PRODUCT_AR', models.BooleanField(max_length=5, null=True)),
                ('MONTH_DELIVERY', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'output_capacity_setting',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='table_output_capacity_setting',
        ),
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='PEAK_CAPACITY',
        ),
    ]
