# Generated by Django 5.2.6 on 2025-10-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0007_remove_table_simulazione_utente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='GEOKEY',
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='POSTALIZZAZIONI',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='PROVINCIA',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='REGIONE',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='CAPACITA',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='RECAPITISTA',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='TIPO_CAPACITA',
            field=models.CharField(max_length=25),
        ),
    ]
