# Generated by Django 5.2.6 on 2025-10-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0007_table_output_capacity_setting_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table_output_capacity_setting',
            table='output_capacity_setting',
        ),
    ]
