# Generated by Django 5.2.6 on 2025-10-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0008_remove_table_capacita_modificate_geokey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='ACTIVATION_DATE_FROM',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='ACTIVATION_DATE_TO',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='CAPACITA',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='MESE_SIMULAZIONE',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='RECAPITISTA',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='SIMULAZIONE_ID',
            field=models.ForeignKey(db_column='SIMULAZIONE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Simulatore.table_simulazione'),
        ),
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='TIPO_CAPACITA',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='table_simulazione',
            name='DESCRIZIONE',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='table_simulazione',
            name='NOME',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='table_simulazione',
            name='STATO',
            field=models.CharField(choices=[('Lavorata', 'Lavorata'), ('In lavorazione', 'In lavorazione'), ('Schedulata', 'Schedulata'), ('Non completata', 'Non completata'), ('Bozza', 'Bozza')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='table_simulazione',
            name='TIMESTAMP_ESECUZIONE',
            field=models.DateTimeField(null=True),
        ),
    ]
