# Generated by Django 5.2.6 on 2025-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0008_view_output_capacity_setting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='CREATED_AT',
        ),
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='GEOKEY',
        ),
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='PK',
        ),
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='PRODUCT_RS',
        ),
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='TENDER_ID',
        ),
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='TENDER_ID_GEOKEY',
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='PROVINCE',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='REGIONE',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='SUM_MONTHLY_ESTIMATE',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='SUM_WEEKLY_ESTIMATE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='PRODUCT_890',
            field=models.BooleanField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='table_capacita_modificate',
            name='PRODUCT_AR',
            field=models.BooleanField(max_length=5, null=True),
        ),
    ]
