# Generated by Django 5.2.6 on 2025-10-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0008_alter_table_output_capacity_setting_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_simulazione',
            name='TRIGGER',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
