# Generated by Django 5.2.6 on 2026-04-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0008_remove_table_capacita_simulate_cap_cod_sigla_provincia_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='table_capacita_simulate_cap',
            index=models.Index(fields=['SIMULAZIONE_ID'], name='indice_simulazione_id_4'),
        ),
    ]
