# Generated by Django 5.2.6 on 2025-10-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0009_alter_table_capacita_modificate_activation_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_simulazione',
            name='STATO',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
