# Generated by Django 5.2.6 on 2026-04-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0009_table_capacita_simulate_cap_indice_simulazione_id_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_vista_fornitore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DELIVERY_DATE', models.CharField(max_length=7, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('GEOKEY', models.CharField(max_length=5, null=True)),
                ('PRODUCT_AR', models.BooleanField(null=True)),
                ('PRODUCT_890', models.BooleanField(null=True)),
                ('MONTHLY_ESTIMATE', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'vista_fornitore',
                'managed': False,
            },
        ),
    ]
