# Generated by Django 5.2.6 on 2025-10-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0009_remove_table_capacita_modificate_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_declared_capacity',
            old_name='TENDERID',
            new_name='TENDER_ID',
        ),
    ]
