# Generated by Django 5.2.6 on 2025-10-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0009_table_simulazione_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_simulazione',
            name='UTENTE_ID',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
