# Generated by Django 5.2.6 on 2026-04-23 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0010_view_vista_fornitore'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_output_residui_ente',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('SENDER_PA_ID', models.CharField(max_length=80, null=True)),
                ('COUNT_RESIDUI', models.IntegerField(null=True)),
                ('SIMULAZIONE_ID', models.ForeignKey(db_column='SIMULAZIONE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Simulatore.table_simulazione')),
            ],
            options={
                'db_table': 'OUTPUT_RESIDUI_ENTE',
                'indexes': [models.Index(fields=['SIMULAZIONE_ID'], name='indice_simulazione_id_5'), models.Index(fields=['SENDER_PA_ID'], name='indice_sender_pa_id_2')],
            },
        ),
    ]
