# Generated by Django 5.2.6 on 2026-04-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0011_table_output_residui_ente'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_vista_ente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DELIVERY_DATE', models.CharField(max_length=7, null=True)),
                ('PA_ID', models.CharField(max_length=80, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('PRODUCT_TYPE', models.CharField(max_length=3, null=True)),
                ('SUM_MONTHLY_ESTIMATE', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'vista_ente',
                'managed': False,
            },
        ),
    ]
