# Generated by Django 5.2.6 on 2025-10-23 08:00

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0011_view_output_edit_capacity_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_output_modified_capacity_setting',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ORIGINAL_CAPACITY', models.IntegerField(null=True)),
                ('MODIFIED_CAPACITY', models.IntegerField(null=True)),
                ('SUM_WEEKLY_ESTIMATE', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('PRODUCT_890', models.BooleanField(max_length=5, null=True)),
                ('PRODUCT_AR', models.BooleanField(max_length=5, null=True)),
                ('MONTH_DELIVERY', models.SmallIntegerField(null=True)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'output_modified_capacity_setting',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='view_output_edit_capacity_setting',
        ),
    ]
