# Generated by Django 5.2.6 on 2026-05-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0012_view_vista_ente'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_tabella_sintesi_ente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SENDER_PA_ID', models.CharField(max_length=80, null=True)),
                ('SUM_COUNT_REQUEST', models.IntegerField(null=True)),
                ('AVG_COUNT_REQUEST', models.DecimalField(decimal_places=5, max_digits=7, null=True)),
                ('SUM_COUNT_RESIDUI', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tabella_sintesi_ente',
                'managed': False,
            },
        ),
    ]
