# Generated by Django 5.2.6 on 2025-10-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0012_view_output_modified_capacity_setting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_capacita_modificate',
            old_name='PROVINCE',
            new_name='COD_SIGLA_PROVINCIA',
        ),
        migrations.AddField(
            model_name='table_capacita_modificate',
            name='PROVINCIA',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
