# Generated by Django 5.2.6 on 2026-05-06 16:53

import Simulatore.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0013_view_tabella_sintesi_ente'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_tabella_sintesi_reg_recap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SENDER_PA_ID', models.CharField(max_length=80, null=True)),
                ('SUM_COUNT_REQUEST', models.IntegerField(null=True)),
                ('AVG_COUNT_REQUEST', models.DecimalField(decimal_places=5, max_digits=7, null=True)),
                ('SUM_COUNT_RESIDUI', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tabella_sintesi_reg_recap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='table_output_residui_reg_recap',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('PROVINCIA_RECAPITISTA', models.CharField(max_length=100, null=True)),
                ('COUNT_RESIDUI', models.IntegerField(null=True)),
                ('SIMULAZIONE_ID', models.ForeignKey(db_column='SIMULAZIONE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Simulatore.table_simulazione')),
            ],
            options={
                'db_table': 'OUTPUT_RESIDUI_REG_RECAP',
                'indexes': [models.Index(fields=['SIMULAZIONE_ID'], name='indice_simulazione_id_6'), models.Index(fields=['PROVINCE'], name='indice_province_3')],
            },
        ),
    ]
