# Generated by Django 5.2.6 on 2025-10-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0013_rename_province_table_capacita_modificate_cod_sigla_provincia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='PROVINCIA',
        ),
    ]
