# Generated by Django 5.2.6 on 2026-05-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0014_view_tabella_sintesi_reg_recap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_output_residui_reg_recap',
            name='SETTIMANA_DELIVERY',
        ),
    ]
