# Generated by Django 5.2.6 on 2025-10-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0014_remove_table_capacita_modificate_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_capacita_modificate',
            name='SUM_MONTHLY_ESTIMATE',
        ),
    ]
