# Generated by Django 5.2.13 on 2026-07-07 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0015_remove_table_output_residui_reg_recap_settimana_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_mock',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DELIVERY_DATE', models.CharField(null=True)),
                ('PA_ID', models.CharField(max_length=80, null=True)),
                ('MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('PRODUCT_TYPE', models.CharField(max_length=80, null=True)),
                ('SUDDIVISIONE_GEOGRAFICA', models.CharField(max_length=80, null=True)),
                ('LAST_UPDATE_TIMESTAMP', models.CharField(max_length=80, null=True)),
                ('ID_SIMULAZIONE', models.ForeignKey(db_column='SIMULAZIONE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Simulatore.table_simulazione')),
            ],
            options={
                'db_table': 'SENDER_LIMIT_MOCK',
            },
        ),
    ]
