# Generated by Django 5.2.13 on 2026-08-05 10:44

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0015_remove_table_output_residui_reg_recap_settimana_delivery'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='table_simulazione',
            name='indice_timestamp_esecuzione',
        ),
        migrations.RenameField(
            model_name='table_simulazione',
            old_name='TIMESTAMP_ESECUZIONE',
            new_name='START_TIMESTAMP',
        ),
        migrations.AddField(
            model_name='table_simulazione',
            name='END_TIMESTAMP',
            field=Simulatore.models.NaiveDateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='table_simulazione',
            index=models.Index(fields=['START_TIMESTAMP'], name='indice_start_timestamp'),
        ),
    ]
