# Generated by Django 5.2.6 on 2025-10-29 15:42

import Simulatore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0015_remove_table_capacita_modificate_sum_monthly_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_output_grafico_ente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('SENDER_PA_ID', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('COUNT_REQUEST', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'output_grafico_ente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_output_grafico_mappa_picchi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('FLAG_PICCO', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'output_grafico_mappa_picchi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='view_output_grafico_reg_recap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('COUNT_REQUEST', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'output_grafico_reg_recap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='table_results',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PK', models.CharField(max_length=80, null=True)),
                ('SK', models.CharField(max_length=80, null=True)),
                ('ATTEMPT', models.IntegerField(null=True)),
                ('CAP', models.CharField(max_length=5, null=True)),
                ('CREATED_AT', Simulatore.models.NaiveDateTimeField(null=True)),
                ('IUN', models.CharField(max_length=80, null=True)),
                ('NOTIFICATION_SENT_AT', Simulatore.models.NaiveDateTimeField(null=True)),
                ('PREPARE_REQUEST_DATE', Simulatore.models.NaiveDateTimeField(null=True)),
                ('PRIORITY', models.IntegerField(null=True)),
                ('PRODUCT_TYPE', models.CharField(max_length=3, null=True)),
                ('PROVINCE', models.CharField(max_length=5, null=True)),
                ('REQUEST_ID', models.CharField(max_length=200, null=True)),
                ('SENDER_PA_ID', models.CharField(max_length=80, null=True)),
                ('TENDER_ID', models.CharField(max_length=8, null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('SETTIMANA_DELIVERY', Simulatore.models.NaiveDateTimeField(null=True)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'RESULTS',
            },
        ),
        migrations.RenameModel(
            old_name='table_capacita_modificate',
            new_name='table_capacita_simulate',
        ),
        migrations.AddField(
            model_name='table_simulazione',
            name='TIPO_SIMULAZIONE',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterModelTable(
            name='table_capacita_simulate',
            table='CAPACITA_SIMULATE',
        ),
    ]
