# Generated by Django 5.2.13 on 2026-08-26 18:03

import Simulatore.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0016_remove_table_simulazione_indice_timestamp_esecuzione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_output_capacity_setting_mock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIMULAZIONE_ID', models.IntegerField(null=True)),
                ('UNIFIED_DELIVERY_DRIVER', models.CharField(max_length=80, null=True)),
                ('ACTIVATION_DATE_FROM', Simulatore.models.NaiveDateTimeField(null=True)),
                ('ACTIVATION_DATE_TO', Simulatore.models.NaiveDateTimeField(null=True)),
                ('CAPACITY', models.IntegerField(null=True)),
                ('PEAK_CAPACITY', models.IntegerField(null=True)),
                ('PRODUCTION_CAPACITY', models.IntegerField(null=True)),
                ('SUM_WEEKLY_ESTIMATE_DEFAULT', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE_DEFAULT', models.IntegerField(null=True)),
                ('SUM_MONTHLY_ESTIMATE_MOCK', models.IntegerField(null=True)),
                ('REGIONE', models.CharField(max_length=50, null=True)),
                ('PROVINCIA', models.CharField(max_length=50, null=True)),
                ('COD_SIGLA_PROVINCIA', models.CharField(max_length=5, null=True)),
                ('PRODUCT_890', models.BooleanField(null=True)),
                ('PRODUCT_AR', models.BooleanField(null=True)),
                ('MONTH_DELIVERY', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'output_capacity_setting_mock',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='table_simulazione',
            name='PIANIFICAZIONE_POSTALIZZAZIONI',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='table_simulazione',
            name='POSTALIZZAZIONI_FUORI_COMMESSA',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='table_sender_limit_mock',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DELIVERY_DATE', models.CharField(null=True)),
                ('PA_ID', models.CharField(max_length=80, null=True)),
                ('MONTHLY_ESTIMATE', models.IntegerField(null=True)),
                ('PRODUCT_TYPE', models.CharField(max_length=80, null=True)),
                ('SUDDIVISIONE_GEOGRAFICA', models.CharField(max_length=80, null=True)),
                ('LAST_UPDATE_TIMESTAMP', Simulatore.models.NaiveDateTimeField(null=True)),
                ('SIMULAZIONE_ID', models.ForeignKey(db_column='SIMULAZIONE_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Simulatore.table_simulazione')),
            ],
            options={
                'db_table': 'SENDER_LIMIT_MOCK',
                'indexes': [models.Index(fields=['SIMULAZIONE_ID'], name='indice_simulazione_id_7'), models.Index(fields=['DELIVERY_DATE'], name='indice_delivery_date_2'), models.Index(fields=['SUDDIVISIONE_GEOGRAFICA'], name='indice_suddivisione_geografica'), models.Index(fields=['LAST_UPDATE_TIMESTAMP'], name='indice_last_update_timestamp_5')],
            },
        ),
    ]
