# Generated by Django 5.2.13 on 2026-07-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0016_table_mock'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_simulazione',
            name='PIANIFICAZIONE_POSTALIZZAZIONI',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='table_simulazione',
            name='POSTALIZZAZIONI_FUORI_COMMESSA',
            field=models.BooleanField(null=True),
        ),
    ]
