# Generated by Django 5.2.13 on 2026-07-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulatore', '0017_table_simulazione_pianificazione_postalizzazioni_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table_mock',
            new_name='table_sender_limit_mock',
        ),
    ]
